#!/usr/bin/env python3

'''
Note: This code is for panel A only. Panels B-E were created the same way but subset to the seasons. 
'''

import glob
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
from shapely.geometry import Point

# List all the CSV files
csv_files = glob.glob("/Volumes/easystore/hourly_precip/cleaned_hourly/*.csv") 

results = []

# Loop through each file and compute the trend
# this takes 1 minute
for file_path in tqdm(csv_files):
    df = pd.read_csv(file_path)
    # dropping missing years as in Barbero 2017
    df = df.dropna(subset=["precip"])  # Remove NaNs
    
    df["year"] = pd.to_datetime(df["DATE"]).dt.year
    grouped = df.groupby("year")["precip"].max().reset_index()
    grouped = grouped[grouped["precip"] > 0] # only keep years where max precip >0, essentially treat zero-max years as NA
    
    results.append(np.median(grouped.precip))

results = np.array(results)
results = (results * 2.54) * 10 # convert inches to mm

stations = gpd.read_file("all_stations.shp")

# Add to DataFrame
stations["results"] = results

# Load states
states = gpd.read_file("cb_2018_us_state_5m.shp")
states = states.to_crs("EPSG:4326")
states = states[states.NAME.isin([
    "Washington", "Oregon", "Idaho", "Montana", "California", "Nevada",
    "Utah", "Wyoming", "Colorado", "Arizona", "New Mexico"
])]

import matplotlib.colors as mcolors

# Define bins and colormap
bounds = np.arange(0, 30.01, 2.5)
cmap = plt.cm.Greens
norm = mcolors.BoundaryNorm(boundaries=bounds, ncolors=cmap.N, clip=True)

# Plotting
fig, ax = plt.subplots(figsize=(10, 8))
states.boundary.plot(ax=ax, edgecolor="k")
stations.plot(ax=ax, column="results", cmap=cmap, norm=norm, 
              markersize=100, edgecolor="black")

# Add colorbar
sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
cbar = plt.colorbar(sm, ax=ax, orientation="horizontal", fraction=0.025, pad=0.002, aspect=45, shrink=0.6)
cbar.ax.tick_params(labelsize=15)
# Annotate each point with its station name
# for x, y, label in zip(gdf.geometry.x, gdf.geometry.y, gdf['station']):
#     ax.annotate(label, xy=(x, y), xytext=(3, 3), textcoords="offset points", fontsize=8)
    

#plt.title("Median 1-hr AMP amounts", fontsize=20, y=0.96)
ax.set_axis_off()
plt.show()

# get domain median
stations.results.median()

